exports.seed = function(knex) {
    return knex('dogs').insert([
        { breed: "American Bulldog", description: "The American Bulldog is stocky and muscular, but also agile and built for chasing down stray cattle and helping out with work on the farm.", imageUrl: "https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2020/01/14144341/American-Bulldog-standing-in-three-quarter-view.jpg"},
        { breed: "Golder Retriever", description: "The Golden Retriever is a medium-large gun dog that was bred to retrieve shot waterfowl, such as ducks and upland game birds, during hunting and shooting parties.", imageUrl: "https://www.idenyt.dk/globalassets/denmark/kaledyr-2/golden-retriever.jpg"},
        { breed: "Rottweiler", description: "The Rottweiler is a breed of domestic dog, regarded as medium-to-large or large.", imageUrl: "https://www.bil-jac.com/media/nhyd0qet/rottweiler-868607572.jpg?center=0.48541458426682293,0.2815947395058393&mode=crop&width=600&height=400&rnd=132169062074100000"},
        { breed: "German Pointer", description: "The German Shorthaired Pointer is a medium to large sized breed of dog developed in the 19th century in Germany for hunting.", imageUrl: "https://www.askideas.com/media/27/Brown-Pointer-Dog-In-Fields.jpg"},
        { breed: "The Dobermann", description: "The Dobermann has a long muzzle. It stands on its pads and is not usually heavy-footed.", imageUrl: "https://www.dobermanplanet.com/wp-content/uploads/2019/02/Strong-Doberman-Large.jpg"},
        { breed: "Dalmatian", description: "The Dalmatian is a breed of large-sized dog, noted for its unique white coat marked with black or liver-coloured spots and used mainly as a carriage dog in its early days.", imageUrl: "https://lh3.googleusercontent.com/proxy/LSVZQpLs-fNlAA7MUCcqbybDZ6EkHmJ4vRg9260LQY_IZCKKN9R3Cz16I2KiAPUsndW8GC-qQF2VWwALrt-w4o1fjHR0g40ZCta2m3lM"},
        { breed: "Samoyed", description: "The Samoyed is a breed of large herding dogs with thick, white, double-layer coats. They are related to the laika, a spitz-type dog. It takes its name from the Samoyedic peoples of Siberia.", imageUrl: "https://www.pets4homes.co.uk/images/articles/4801/large/how-much-grooming-does-a-samoyed-dog-need-5b150a0cf3dad.jpg"},
        { breed: "German Shepherd", description: "The German Shepherd is a breed of medium to large-sized working dog that originated in Germany.", imageUrl: "https://www.anythinggermanshepherd.com/wp-content/uploads/2019/12/male-vs-female-german-shepherd.jpg"},
        { breed: "Saint Bernard", description: "The St. Bernard or St Bernard is a breed of very large working dog from the western Alps in Italy and Switzerland.", imageUrl: "https://toppng.com/uploads/preview/barrel-dog-muzzle-saint-bernard-wallpaper-11555167597secbmh81u5.jpg"},
        { breed: "Labradoodle", description: "A Labradoodle is a crossbreed dog created by crossing the Labrador retriever and the Standard, Miniature, or Toy poodle.", imageUrl: "https://i1.wp.com/blog.dogley.com/dk/wp-content/uploads/sites/3/2019/11/Labradoodle_1.jpg?fit=1435%2C905&ssl=1"},
        { breed: "Australian Shepherd", description: 'The Australian Shepherd, often known simply as the "Aussie", is a medium-sized breed of dog that was, despite its name, developed on ranches in the United States during the 19th century.', imageUrl: "https://i.pinimg.com/originals/d7/ca/6d/d7ca6de2deb3430e5f780af2a4266e37.jpg"}
    ])
}